#!/bin/sh
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ls="ls -hN --color=auto --group-directories-first" \
	diff="diff --color=auto" \
	ka="killall" \
	p="sudo pacman" \
	merge='xrdb -merge ~/.Xresources' \
 	ll="ls -l" \
	lla="ls -lA" \
	la="ls -a" \
	..='cd ..' \
	h='cd ~/' \
	mousepad='devour mousepad' \
	mpv='devour mpv' \
	sxiv='devour sxiv' \
	zathura='devour zathura' \
	zathura='devour zathura' \

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"


# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'
