#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          8
bspc config single_monocle      true
bspc config borderless_singleton	true

single_monocle

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a xdman-Main state=floating

dunst &
nitrogen --restore &
picom &
lxsession &
mate-power-manager &
xss-lock --transfer-sleep-lock -- i3lock -i ~/Pictures/a.png &
xsetroot -cursor_name left_ptr &