#!/bin/sh

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ka="killall" \
	p="sudo pacman" \
	merge='xrdb -merge ~/.Xresources' \
 	ll="ls -l" \
	lla="ls -lA" \
	la="ls -a" \
	..='cd ..' \
	h='cd ~/' \
	c='clear' \
	stowvt='stow -vt ~' \   
